version: "2"

services:

# ------> node ------>
    node_22i7v46jlxywfjh:
        container_name: node_22i7v46jlxywfjh
        image: node:10.5-alpine
        user: "node"
        working_dir: /node
        volumes:
            - .././:/node
        environment:
            NODE_ENV: dev
        expose:
            - 8081
# <------ node <------